include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  rules:
    - always_use_package_imports
    - avoid-unused-parameters
    - avoid_print
    - no-equal-then-else
